sonar.host.url=https://sonarcloud.io
sonar.projectKey=embeddable-hq_remarkable-pro
sonar.organization=embeddable-com
sonar.sources=.
sonar.exclusions= **/*.types.ts, **/*.stories.tsx, **/*.test.ts, **/*.test.tsx, **/**emb.ts, **/**.css, **/**definition.ts
sonar.coverage.exclusions=scripts/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
