import { styles } from '@embeddable.com/remarkable-ui/styles';

const stylesRemarkablePro = {
  // Filter Builder
  '--em-filterbuilder-gap': 'var(--em-core-spacing--0300)',
  '--em-filterbuilder-font-family': 'var(--em-core-font-family--base)',
  '--em-filterbuilder-font-weight': 'var(--em-core-font-weight--medium)',
  '--em-filterbuilder-font-size': 'var(--em-core-font-size--xs)',
  '--em-filterbuilder-filter-gap': 'var(--em-core-spacing--0050)',
  '--em-filterbuilder-add-button-height': 'var(--em-core-size--0800)',
  '--em-filterbuilder-add-button-gap': 'var(--em-core-spacing--0050)',
  '--em-filterbuilder-add-button-border-width': 'var(--em-core-border-width--000)',
  '--em-filterbuilder-add-button-border-color': 'rgb(255 255 255 / 0%)',
  '--em-filterbuilder-add-button-background': 'var(--em-sem-background--light)',
  '--em-filterbuilder-add-button-background--hover': 'var(--em-sem-background--subtle)',
  '--em-filterbuilder-add-button-padding-y': 'var(--em-core-spacing--0000)',
  '--em-filterbuilder-add-button-padding-x': 'var(--em-core-spacing--0300)',
  '--em-filterbuilder-add-button-border-radius': 'var(--em-core-border-radius--400)',
  '--em-filterbuilder-add-button-color': 'var(--em-sem-text--neutral)',
  '--em-filterbuilder-add-button-icon-size': 'var(--em-core-size--0400)',
  '--em-filterbuilder-member-button-height': 'var(--em-core-size--0800)',
  '--em-filterbuilder-member-button-border-width': 'var(--em-core-border-width--000)',
  '--em-filterbuilder-member-button-border-color': 'rgb(255 255 255 / 0%)',
  '--em-filterbuilder-member-button-background': 'var(--em-sem-background--light)',
  '--em-filterbuilder-member-button-background--hover': 'var(--em-sem-background--subtle)',
  '--em-filterbuilder-member-button-padding-y': 'var(--em-core-spacing--0000)',
  '--em-filterbuilder-member-button-padding-x': 'var(--em-core-spacing--0300)',
  '--em-filterbuilder-member-button-border-left-radius': 'var(--em-core-border-radius--400)',
  '--em-filterbuilder-member-button-border-right-radius': 'var(--em-core-border-radius--100)',
  '--em-filterbuilder-delete-button-height': 'var(--em-core-size--0800)',
  '--em-filterbuilder-delete-button-border-width': 'var(--em-core-border-width--000)',
  '--em-filterbuilder-delete-button-border-color': 'rgb(255 255 255 / 0%)',
  '--em-filterbuilder-delete-button-background': 'var(--em-sem-background)',
  '--em-filterbuilder-delete-button-background--hover': 'var(--em-sem-background--subtle)',
  '--em-filterbuilder-delete-button-padding-y': 'var(--em-core-spacing--0100)',
  '--em-filterbuilder-delete-button-padding-x': 'var(--em-core-spacing--0100)',
  '--em-filterbuilder-delete-button-color': 'var(--em-sem-text--muted)',
  '--em-filterbuilder-delete-button-border-left-radius': 'var(--em-core-border-radius--100)',
  '--em-filterbuilder-delete-button-border-right-radius': 'var(--em-core-border-radius--400)',
  '--em-filterbuilder-delete-button-icon-size': 'var(--em-core-size--0400)',
  '--em-filterbuilder-operator-button-height': 'var(--em-core-size--0800)',
  '--em-filterbuilder-operator-button-border-width': 'var(--em-core-border-width--000)',
  '--em-filterbuilder-operator-button-border-color': 'rgb(255 255 255 / 0%)',
  '--em-filterbuilder-operator-button-background': 'var(--em-sem-background)',
  '--em-filterbuilder-operator-button-background--hover': 'var(--em-sem-background--subtle)',
  '--em-filterbuilder-operator-button-padding-y': 'var(--em-core-spacing--0100)',
  '--em-filterbuilder-operator-button-padding-x': 'var(--em-core-spacing--0100)',
  '--em-filterbuilder-operator-button-color': 'var(--em-sem-text--muted)',
  '--em-filterbuilder-operator-button-border-left-radius': 'var(--em-core-border-radius--100)',
  '--em-filterbuilder-operator-button-border-right-radius': 'var(--em-core-border-radius--100)',
  '--em-filterbuilder-value-button-height': 'var(--em-core-size--0800)',
  '--em-filterbuilder-value-button-gap': 'var(--em-core-spacing--0050)',
  '--em-filterbuilder-value-button-border-width': 'var(--em-core-border-width--000)',
  '--em-filterbuilder-value-button-border-color': 'rgb(255 255 255 / 0%)',
  '--em-filterbuilder-value-button-background': 'var(--em-sem-background--light)',
  '--em-filterbuilder-value-button-background--hover': 'var(--em-sem-background--subtle)',
  '--em-filterbuilder-value-button-padding-y': 'var(--em-core-spacing--0000)',
  '--em-filterbuilder-value-button-padding-x': 'var(--em-core-spacing--0300)',
  '--em-filterbuilder-value-button-border-left-radius': 'var(--em-core-border-radius--100)',
  '--em-filterbuilder-value-button-border-right-radius': 'var(--em-core-border-radius--100)',
  '--em-filterbuilder-value-button-color': 'var(--em-sem-text--neutral)',
  '--em-filterbuilder-value-button-icon-size': 'var(--em-core-size--0400)',
  '--em-filterbuilder-value-button-min-width': 'var(--em-core-size--1000)',
  '--em-filterbuilder-clear-button-height': 'var(--em-core-size--0800)',
  '--em-filterbuilder-clear-button-border-width': 'var(--em-core-border-width--000)',
  '--em-filterbuilder-clear-button-border-color': 'rgb(255 255 255 / 0%)',
  '--em-filterbuilder-clear-button-background': 'transparent',
  '--em-filterbuilder-clear-button-background--hover': 'var(--em-sem-background--light)',
  '--em-filterbuilder-clear-button-padding-y': 'var(--em-core-spacing--0000)',
  '--em-filterbuilder-clear-button-padding-x': 'var(--em-core-spacing--0300)',
  '--em-filterbuilder-clear-button-border-radius': 'var(--em-core-border-radius--400)',
  '--em-filterbuilder-clear-button-color': 'var(--em-sem-text--muted)',
  '--em-filterbuilder-scroll-right-button-height': 'var(--em-core-size--0800)',
  '--em-filterbuilder-scroll-right-button-border-width': 'var(--em-core-border-width--000)',
  '--em-filterbuilder-scroll-right-button-border-color': 'rgb(255 255 255 / 0%)',
  '--em-filterbuilder-scroll-right-button-background': 'transparent',
  '--em-filterbuilder-scroll-right-button-background--hover': 'var(--em-sem-background--light)',
  '--em-filterbuilder-scroll-right-button-padding-y': 'var(--em-core-spacing--0000)',
  '--em-filterbuilder-scroll-right-button-padding-x': 'var(--em-core-spacing--0300)',
  '--em-filterbuilder-scroll-right-button-border-left-radius': 'var(--em-core-border-radius--100)',
  '--em-filterbuilder-scroll-right-button-border-right-radius': 'var(--em-core-border-radius--400)',
  '--em-filterbuilder-scroll-right-button-color': 'var(--em-sem-text--neutral)',
  '--em-filterbuilder-scroll-right-button-icon-size': 'var(--em-core-size--0400)',
  '--em-filterbuilder-scroll-left-button-height': 'var(--em-core-size--0800)',
  '--em-filterbuilder-scroll-left-button-border-width': 'var(--em-core-border-width--000)',
  '--em-filterbuilder-scroll-left-button-border-color': 'rgb(255 255 255 / 0%)',
  '--em-filterbuilder-scroll-left-button-background': 'transparent',
  '--em-filterbuilder-scroll-left-button-background--hover': 'var(--em-sem-background--light)',
  '--em-filterbuilder-scroll-left-button-padding-y': 'var(--em-core-spacing--0000)',
  '--em-filterbuilder-scroll-left-button-padding-x': 'var(--em-core-spacing--0300)',
  '--em-filterbuilder-scroll-left-button-border-left-radius': 'var(--em-core-border-radius--400)',
  '--em-filterbuilder-scroll-left-button-border-right-radius': 'var(--em-core-border-radius--100)',
  '--em-filterbuilder-scroll-left-button-color': 'var(--em-sem-text--neutral)',
  '--em-filterbuilder-scroll-left-button-icon-size': 'var(--em-core-size--0400)',
  '--em-filterbuilder-value-input-height': 'var(--em-core-size--0800)',
  '--em-filterbuilder-value-input-border-width': 'var(--em-core-border-width--000)',
  '--em-filterbuilder-value-input-border-color': 'rgb(255 255 255 / 0%)',
  '--em-filterbuilder-value-input-padding-y': 'var(--em-core-spacing--0000)',
  '--em-filterbuilder-value-input-padding-x': 'var(--em-core-spacing--0300)',
  '--em-filterbuilder-value-input-border-left-radius': 'var(--em-core-border-radius--100)',
  '--em-filterbuilder-value-input-border-right-radius': 'var(--em-core-border-radius--100)',
  '--em-filterbuilder-value-input-color': 'var(--em-sem-text--neutral)',
  '--em-filterbuilder-value-input-min-width': 'var(--em-core-size--1200)',
  '--em-filterbuilder-value-input-background': 'var(--em-sem-background--light)',
  '--em-filterbuilder-value-input-background--hover': 'var(--em-sem-background--subtle)',
  '--em-filterbuilder-andor-button-height': 'var(--em-core-size--0800)',
  '--em-filterbuilder-andor-button-border-width': 'var(--em-core-border-width--000)',
  '--em-filterbuilder-andor-button-border-color': 'rgb(255 255 255 / 0%)',
  '--em-filterbuilder-andor-button-background': 'var(--em-sem-background--light)',
  '--em-filterbuilder-andor-button-background--hover': 'var(--em-sem-background--subtle)',
  '--em-filterbuilder-andor-button-padding-y': 'var(--em-core-spacing--0000)',
  '--em-filterbuilder-andor-button-padding-x': 'var(--em-core-spacing--0300)',
  '--em-filterbuilder-andor-button-border-radius': 'var(--em-core-border-radius--400)',
  '--em-filterbuilder-andor-button-color': 'var(--em-sem-text--neutral)',

  // Filter Builder with grouping (segment tokens)
  '--em-filter-gap--internal': 'var(--em-core-spacing--0050)',
  '--em-filter-gap--external': 'var(--em-core-spacing--0300)',
  '--em-filter-gap--andor': 'var(--em-core-spacing--0100)',
  '--em-filter-height': 'var(--em-core-size--0800)',
  '--em-filter-icon-size': 'var(--em-core-size--0400)',
  '--em-filter-padding-x': 'var(--em-core-spacing--0300)',
  '--em-filter-padding-x--operator': 'var(--em-core-spacing--0100)',
  '--em-filter-padding-y': 'var(--em-core-spacing--0000)',
  '--em-filter-border-width': 'var(--em-core-border-width--000)',
  '--em-filter-border-color': 'rgb(255 255 255 / 0%)',
  '--em-filter-border-radius': 'var(--em-core-border-radius--000)',
  '--em-filter-border-radius--group': 'var(--em-core-border-radius--400)',
  '--em-filter-color': 'var(--em-sem-text--neutral)',
  '--em-filter-color--operator': 'var(--em-sem-text--muted)',
  '--em-filter-background--filter': 'var(--em-sem-background--light)',
  '--em-filter-background--filter--hover': 'var(--em-sem-background--subtle)',
  '--em-filter-background--operator': 'var(--em-sem-background)',
  '--em-filter-background--operator--hover': 'var(--em-sem-background--subtle)',
  '--em-filter-background--group': 'var(--em-sem-background--neutral)',
  '--em-filter-background--chevron': 'var(--em-sem-background--neutral)',
  '--em-filter-border-color--group': 'var(--em-sem-background--light)',
  '--em-filter-border-width--group': 'var(--em-core-border-width--025)',
  '--em-filter-padding--group': 'var(--em-core-spacing--0100)',
  '--em-filter-opacity--disabled': '0.5',
  '--em-filter-value-input-min-width': 'var(--em-core-size--0800)',

  // Drilldown Modal
  '--em-drilldown-modal-min-height': '100%',
  '--em-drilldown-modal-width': '100%',

  // Canvas Overlay
  '--em-canvas-overlay-position': 'fixed',
  '--em-canvas-overlay-inset': '0',
  '--em-canvas-overlay-backdrop-background': 'var(--em-overlay-background)',
  '--em-canvas-overlay-content-background': 'transparent',
  '--em-canvas-overlay-width': '100%',
  '--em-canvas-overlay-max-width': '78rem',
  '--em-canvas-overlay-height': 'auto',
  '--em-canvas-overlay-max-height': 'none',
  '--em-canvas-overlay-padding': '0 2rem 2.25rem',
  '--em-canvas-overlay-border-radius': '1.75rem',
  '--em-canvas-overlay-title-color': 'var(--em-sem-text--inverted)',
  '--em-canvas-overlay-action-button-color': 'var(--em-buttonicon-color--secondary)',
  '--em-canvas-overlay-action-button-background': 'var(--em-buttonicon-background--secondary)',
  '--em-canvas-overlay-action-button-border-color': 'var(--em-buttonicon-border-color--secondary)',
  '--em-canvas-overlay-action-button-border-width': 'var(--em-buttonicon-border-width)',
  '--em-canvas-overlay-action-button-border-radius': 'var(--em-buttonicon-border-radius)',
  '--em-canvas-overlay-actions-justify-content': 'center',
  '--em-canvas-overlay-actions-position': 'sticky',
  '--em-canvas-overlay-actions-grid-column': '1 / 2',
  '--em-canvas-overlay-actions-grid-row': '2 / 3',
  '--em-canvas-overlay-actions-justify-self': 'center',
  '--em-canvas-overlay-actions-align-self': 'end',
  '--em-canvas-overlay-grid-template-columns': 'repeat(3, minmax(22rem, 1fr))',
  '--em-canvas-overlay-grid-template-columns--tablet': 'repeat(2, minmax(0, 1fr))',
  '--em-canvas-overlay-grid-template-columns--mobile': '1fr',
  '--em-canvas-overlay-grid-auto-rows': 'var(--em-core-spacing--0200)',
  '--em-canvas-overlay-grid-auto-flow': 'dense',
  '--em-canvas-overlay-grid-gap': 'var(--em-core-spacing--0400)',
  '--em-canvas-overlay-grid-align-items': 'start',
  '--em-canvas-overlay-configurator-grid-template-columns': 'minmax(25rem, 30rem) 1fr',
  '--em-canvas-overlay-configurator-grid-template-columns--tablet': '1fr',
  '--em-canvas-overlay-configurator-grid-template-columns--mobile': '1fr',
  '--em-canvas-overlay-configurator-gap': 'var(--em-core-spacing--0800)',
  '--em-canvas-overlay-configurator-form-background': 'var(--em-sem-background--neutral)',
  '--em-canvas-overlay-configurator-form-padding': 'var(--em-core-spacing--0800)',
  '--em-canvas-overlay-configurator-form-padding-bottom': 'var(--em-core-spacing--2000)',
  '--em-canvas-overlay-configurator-form-border-radius': 'var(--em-card-border-radius)',
  '--em-canvas-overlay-configurator-form-gap': 'var(--em-core-spacing--0800)',
};

export type StylesRemarkablePro = typeof stylesRemarkablePro;

// Merge base styles with remarkable pro styles
export const remarkableThemeStyles = { ...styles, ...stylesRemarkablePro } as const;
